name: DG Fangshui Monitor

on:
  schedule:
    - cron: "*/1 * * * *"  # 每分钟执行一次
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests playwright
          playwright install chromium

      - name: Run script
        run: python main.py
